# Quick Introduction to PyTorch


In [3]:
## In this section, we will practice how to use PyTorch to operation matrix addtion, subbraction, multiplication.

In [6]:
# import pytorch library to help us create matrices (also known as tensors)
import torch

# create matrix / tensor A
A = torch.tensor([[1, 2], [5, 8]])

# create matrix/ tensor B
B = torch.tensor([[4, 5], [2, 1]])

In [7]:
print(A)

tensor([[1, 2],
        [5, 8]])


In [5]:
print(B)

tensor([[4, 5],
        [2, 1]])


In [8]:
# matrix addition

C = A + B
print(C)

tensor([[5, 7],
        [7, 9]])


In [9]:
# matrix subtraction
D = A - B
print(D)

tensor([[-3, -3],
        [ 3,  7]])


In [10]:
# matrix multiply

E = A @ B

print(E)

tensor([[ 8,  7],
        [36, 33]])


In [11]:
# other method to multply matrix:
K = torch.matmul(A, B)
print(K)

tensor([[ 8,  7],
        [36, 33]])


> Note: Deep Learning is a bunch of matrix multiplication and addition.
