# Quick Introduction to PyTorch


In [1]:
## In this section, we will practice how to use PyTorch to operation matrix addtion, subbraction, multiplication.

In [2]:
# import pytorch library to help us create matrices (also known as tensors)
import torch
# import torch.nn as nn

# create matrix / tensor A
A = torch.tensor([[1, 2], [5, 8]])

# create matrix/ tensor B
B = torch.tensor([[4, 5], [2, 1]])

In [3]:
print(A)

tensor([[1, 2],
        [5, 8]])


In [4]:
print(B)

tensor([[4, 5],
        [2, 1]])


In [5]:
# matrix addition

C = A + B
print(C)

tensor([[5, 7],
        [7, 9]])


In [6]:
# matrix subtraction
D = A - B
print(D)

tensor([[-3, -3],
        [ 3,  7]])


In [7]:
# matrix multiply

E = A @ B

print(E)

tensor([[ 8,  7],
        [36, 33]])


In [8]:
# other method to multply matrix:
K = torch.matmul(A, B)
print(K)

tensor([[ 8,  7],
        [36, 33]])


> Note: Deep Learning is a bunch of matrix multiplication and addition.


# To Learn more about

```
In Single Layer Perceptron (SLP), we have the following things:

  1) Inputs: X
  2) Weights: W
  3) Predicted Output: Y_pred = X @ W
  4) Targets: Y  (it will be given in supervised learning)

```


In [9]:
# In deep learning, the first algorithm to learn is single layer perceptron.
# It is a simple algorithm that can be used to solve classification (if sigmoid is used as final layer) or forcasting problems.

# Here is an example of logistic regression. Assume, you are given an input X, which has five rows and each row has two columns (features).

X = torch.arange(-10, 11, step=1).reshape(-1, 1)

# change X to float
X = X.float()

X  # check, X is our input data

tensor([[-10.],
        [ -9.],
        [ -8.],
        [ -7.],
        [ -6.],
        [ -5.],
        [ -4.],
        [ -3.],
        [ -2.],
        [ -1.],
        [  0.],
        [  1.],
        [  2.],
        [  3.],
        [  4.],
        [  5.],
        [  6.],
        [  7.],
        [  8.],
        [  9.],
        [ 10.]])

In [10]:
X.shape  # our input data, X, has 21 rows and 1 column (feature)

torch.Size([21, 1])

In [11]:
Y = 2 * X
Y

tensor([[-20.],
        [-18.],
        [-16.],
        [-14.],
        [-12.],
        [-10.],
        [ -8.],
        [ -6.],
        [ -4.],
        [ -2.],
        [  0.],
        [  2.],
        [  4.],
        [  6.],
        [  8.],
        [ 10.],
        [ 12.],
        [ 14.],
        [ 16.],
        [ 18.],
        [ 20.]])

In [12]:
W = torch.randn(X.shape[1], 1)
W

tensor([[0.1402]])

In [13]:
Y_pred = X @ W

Y_pred

tensor([[-1.4016],
        [-1.2614],
        [-1.1213],
        [-0.9811],
        [-0.8410],
        [-0.7008],
        [-0.5606],
        [-0.4205],
        [-0.2803],
        [-0.1402],
        [ 0.0000],
        [ 0.1402],
        [ 0.2803],
        [ 0.4205],
        [ 0.5606],
        [ 0.7008],
        [ 0.8410],
        [ 0.9811],
        [ 1.1213],
        [ 1.2614],
        [ 1.4016]])

In [18]:
# Now, let's build a simple model that predicts Y = 2 * X
class SingleLayerPerceptron:
    def __init__(self, input_size, learning_rate=0.001):
        super(SingleLayerPerceptron, self).__init__()
        self.W = torch.zeros(input_size, 1)
        self.learning_rate = learning_rate
        self.dW = 0.0  # gradients

    def forward(self, X):
        Y_pred = X @ self.W
        return Y_pred

    def backward(self, X, Y_pred, Y):
        # derivate of MSELoss w.r.t W: 2 * X * (Y_pred - Y)
        diff = Y_pred - Y
        # print("num of samples = ", len(X))
        self.dW = 2 * (X.T @ diff) / len(X)

    def step(self):
        # print(self.dW.shape)
        self.W -= self.dW * self.learning_rate

In [19]:
def train_model(model, X, Y, epochs):
    for epoch in range(epochs):
        print(f"Model's Weight at epoch: {epoch + 1} = {model.W.item():.3f}")
        Y_pred = model.forward(X)
        model.backward(X, Y_pred, Y)
        model.step()


input_size = X.shape[1]
model = SingleLayerPerceptron(input_size)
epochs = 100  # number of times our model sees the data: X

# train our model
train_model(model, X, Y, epochs)

Model's Weight at epoch: 1 = 0.000
Model's Weight at epoch: 2 = 0.147
Model's Weight at epoch: 3 = 0.283
Model's Weight at epoch: 4 = 0.409
Model's Weight at epoch: 5 = 0.525
Model's Weight at epoch: 6 = 0.633
Model's Weight at epoch: 7 = 0.734
Model's Weight at epoch: 8 = 0.826
Model's Weight at epoch: 9 = 0.913
Model's Weight at epoch: 10 = 0.992
Model's Weight at epoch: 11 = 1.066
Model's Weight at epoch: 12 = 1.135
Model's Weight at epoch: 13 = 1.198
Model's Weight at epoch: 14 = 1.257
Model's Weight at epoch: 15 = 1.311
Model's Weight at epoch: 16 = 1.362
Model's Weight at epoch: 17 = 1.409
Model's Weight at epoch: 18 = 1.452
Model's Weight at epoch: 19 = 1.492
Model's Weight at epoch: 20 = 1.529
Model's Weight at epoch: 21 = 1.564
Model's Weight at epoch: 22 = 1.596
Model's Weight at epoch: 23 = 1.626
Model's Weight at epoch: 24 = 1.653
Model's Weight at epoch: 25 = 1.678
Model's Weight at epoch: 26 = 1.702
Model's Weight at epoch: 27 = 1.724
Model's Weight at epoch: 28 = 1.744
M

In [20]:
# Let's make a predict: y_pred = W * x = 1.999  * 11.0 = 21.98
y_pred = model.forward(torch.tensor(11.0).reshape(1, 1))
y_pred.item()

21.989168167114258

In [21]:
# Now, let's predict if x is 200, what is y going to be:
# using our mathematical equation: y = 2  * 200 + 1 = 401
y_pred = model.forward(torch.tensor(200.0).reshape(1, 1))
y_pred.item()

399.80303955078125

```
We implmented this simple model, that predicts y = 2 * x, from scratch. Likewise, we can use functionalities provided in pytorch to implement other simple or advanced models from scratch, very easily. For instance, you can see another simple classification model implemented models.py file using PyTorch.
```
